GET /img/foo.png HTTP/1.1
Accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7
Cache-Control: no-cache
Connection: keep-alive
Cookie: Idea-e0e9b1cc=0cc96734-9b6a-42df-aa53-45f2cd7dff5e; username-localhost-8888="2|1:0|10:1709214839|23:username-localhost-8888|44:ZDY0ODJiMmY4NGM2NDU2YWEzZDQ4OTk4NWJjODBhNTU=|df7c9dab59a91023caebf10057fa4537173d296dddb6be7fe1fc38e2ae1273e4"; _xsrf=2|51640482|80190192253bdb2148f3cbcd750f567b|1709214839; sid=xB78FioYxt
Host: localhost:8080
Pragma: no-cache
Referer: http://localhost:8080/
Sec-Fetch-Dest: image
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
sec-ch-ua: "Chromium";v="122", "Not(A:Brand";v="24", "Google Chrome";v="122"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"